lib: [
  "_build/install/default/lib/why3gospel/META"
  "_build/install/default/lib/why3gospel/dune-package"
  "_build/install/default/lib/why3gospel/opam"
]
lib_root: [
  "_build/install/default/lib/why3/plugins/plugin_why3gospel.cmxs" {"why3/plugins/plugin_why3gospel.cmxs"}
]
share_root: [
  "_build/install/default/share/why3/stdlib/gospel.mlw" {"why3/stdlib/gospel.mlw"}
]
doc: [
  "_build/install/default/doc/why3gospel/LICENSE"
  "_build/install/default/doc/why3gospel/README.md"
]
