lib: [
  "_build/install/default/lib/cameleer/META"
  "_build/install/default/lib/cameleer/dune-package"
  "_build/install/default/lib/cameleer/opam"
]
lib_root: [
  "_build/install/default/lib/why3/plugins/plugin_cameleer.cmxs" {"why3/plugins/plugin_cameleer.cmxs"}
]
bin: [
  "_build/install/default/bin/cameleer"
]
share_root: [
  "_build/install/default/share/why3/stdlib/ocamlstdlib.mlw" {"why3/stdlib/ocamlstdlib.mlw"}
]
doc: [
  "_build/install/default/doc/cameleer/LICENSE"
  "_build/install/default/doc/cameleer/README.md"
]
